USE HospitalManagementSystem
--DQL
--Retrieve all appointments for a specific doctor on a given date
SELECT * FROM Appointments
WHERE DoctorID = @DoctorID AND AppointmentDate = @AppointmentDate;

--List all patients who have  visited in the past month 
SELECT * FROM Patients
WHERE PatientID  IN (
    SELECT PatientID FROM Appointments
    WHERE AppointmentDate > DATEADD(month, -1, GETDATE())
)
order by PatientID 

--Generate a report of total revenue generated by each department
SELECT DepartmentName , SUM(Amount) AS"Total Revenue"
from Billing b join Appointments a 
on b.AppointmentID = a.AppointmentID
join Doctors d 
on a.DoctorID = d.DoctorID 
join Departments dp
on d.DepartmentID = dp.DepartmentID
group by DepartmentName;
--List of Diagnosis , Treatment,and Prescription for each patient 
select FirstName+' '+LastName as "Patient Name" ,MedicalHistory , Diagnosis , Treatment , Prescription 
from Patients p join MedicalRecords m 
on p.PatientID = m.PatientID 
order by FirstName;

select p.FirstName +' '+p.LastName As "Patient Name" , b.Amount , b.PaymentStatus , d.FirstName +' '+d.LastName As "Doctor Name" , dp.DepartmentName 
from Billing b join Patients p 
on b.PatientID = p.PatientID 
join Appointments ap on ap.PatientID = p.PatientID 
join Doctors d on ap.DoctorID = d.DoctorID 
join Departments dp on d.DepartmentID=dp.DepartmentID

SELECT FirstName 
from Doctors
union 
select FirstName 
from Patients
order by FirstName